In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import numpy.random as random
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
%precision 3

'%.3f'

In [2]:
sample_array = np.arange(10)
print('sample_array : ', sample_array)

sample_array :  [0 1 2 3 4 5 6 7 8 9]


In [3]:
print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [4]:
sample_array_slice[0:3] = 10
print(sample_array_slice)
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [5]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [6]:
sample_names = np.array(['a', 'b', 'c', 'd', 'e'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'e']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [7]:
sample_names == 'a'

array([ True, False, False, False, False])

In [8]:
data[sample_names =='a']

array([[1.764, 0.4  , 0.979, 2.241, 1.868]])

In [9]:
cond_data = np.array([True, True, False, False, True])
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])
print(np.where(cond_data, x_array, y_array))

[  1   2 300 400   5]


In [10]:
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [12]:
data[sample_names == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [13]:
data[sample_names != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [15]:
cond_data = np.array([False, False, True, True, False])
x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])
print(np.where(cond_data, x_array, y_array))

[ 6  7  3  4 10]


In [17]:
cond_data = np.array([True, True, False, False, True])
print(np.unique(cond_data))

[False  True]


In [18]:
sample_data = np.arange(10)
print('원본 데이터 : ', sample_data)
print('모든 원소의 제곱근 : ', np.sqrt(sample_data))
print('모든 원소의 자연상수 지수함수 : ', np.exp(sample_data))

원본 데이터 :  [0 1 2 3 4 5 6 7 8 9]
모든 원소의 제곱근 :  [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
모든 원소의 자연상수 지수함수 :  [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [20]:
sample_multi_array_data1 = np.arange(9).reshape(3, 3)
print(sample_multi_array_data1)
print('최솟값 : ', sample_multi_array_data1.min())
print('최댓값 : ', sample_multi_array_data1.max())
print('평균 : ', sample_multi_array_data1.mean())
print('합계 : ', sample_multi_array_data1.sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
최솟값 :  0
최댓값 :  8
평균 :  4.0
합계 :  36


In [21]:
cond_data = np.array([True, True, False, False, True])
print('True가 하나라도 있는지', cond_data.any())
print('모두 True인가', cond_data.all())

True가 하나라도 있는지 True
모두 True인가 False


In [26]:
print(sample_multi_array_data1)
print('5보다 큰 숫자가 몇 개인가 : ', (sample_multi_array_data1>5).sum())
print('대각성분 : ', np.diag(sample_multi_array_data1))
print('대각성분의 합 : ',np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5보다 큰 숫자가 몇 개인가 :  3
대각성분 :  [0 4 8]
대각성분의 합 :  12


In [27]:
sample_multi_array_data2 = np.arange(16).reshape(4, 4)
sample_multi_array_data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
print('대각성분의 합 : ', np.trace(sample_multi_array_data2))

대각성분의 합 :  30


In [31]:
sample_array3 = np.array([[1,2,3], [4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
sample_array_vstack = np.concatenate([sample_array3, sample_array4])

In [38]:
first, second, third = np.split(sample_array_vstack, [1,3])

In [41]:
print(first, third)

[[1 2 3]] [[10 11 12]]


In [42]:
sample_array5 = np.array([[13,14,15], [16,17,18], [19,20,21]])
sample_array_vstack2 = np.concatenate([sample_array3,sample_array4,sample_array5])
print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [54]:
first, second, third, fourth = np.split(sample_array_vstack2, [1,2,3])
print('-첫 번째 : \n', first, '\n')
print('-두 번째 : \n', second, '\n')
print('-세 번째 : \n', third, '\n')
print('-네 번째 : \n', fourth, '\n')

-첫 번째 : 
 [[1 2 3]] 

-두 번째 : 
 [[4 5 6]] 

-세 번째 : 
 [[7 8 9]] 

-네 번째 : 
 [[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 



In [66]:
sample_array = np.arange(10)
print(sample_array + 3)

sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12,24).reshape(3,4)
concat_array = np.concatenate([sample_array1, sample_array2], axis=0)
concat_array

[ 3  4  5  6  7  8  9 10 11 12]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
sample_list = [1,2,3,4,5]
sample_list = np.array(sample_list) + 3

In [72]:
sample_list = list(sample_list)